// src/App.tsx
import React, { useEffect } from 'react'
import AppRouter from './router'

const App: React.FC = () => {
  useEffect(() => {
    // Apply dark theme by default
    document.documentElement.classList.add('dark')
  }, [])

  return (
    <div className="dark">
      <AppRouter />
    </div>
  )
}

export default App

// src/App.vue
<script setup lang="ts">
import { onMounted } from 'vue'
import DefaultLayout from './layouts/DefaultLayout.vue'

onMounted(() => {
  // Apply dark theme by default
  document.documentElement.classList.add('dark')
})
</script>

<template>
  <div class="dark">
    <DefaultLayout />
  </div>
</template>
